PLAYERS = [
    {"name": "Aryna Sabalenka",      "slug": "Aryna_Sabalenka",      "instagram": "arynasabalenka",       "ranking": 1},
    {"name": "Elena Rybakina",       "slug": "Elena_Rybakina",       "instagram": "elenarybakina",        "ranking": 2},
    {"name": "Iga Świątek",          "slug": "Iga_Świątek",          "instagram": "iga.swiatek",          "ranking": 3},
    {"name": "Coco Gauff",           "slug": "Coco_Gauff",           "instagram": "cocogauff",            "ranking": 4},
    {"name": "Jessica Pegula",       "slug": "Jessica_Pegula",       "instagram": "jessicapegula",        "ranking": 5},
    {"name": "Amanda Anisimova",     "slug": "Amanda_Anisimova",     "instagram": "amandaanisimova",      "ranking": 6},
    {"name": "Mirra Andreeva",       "slug": "Mirra_Andreeva",       "instagram": "mirraandreeva",        "ranking": 7},
    {"name": "Jasmine Paolini",      "slug": "Jasmine_Paolini",      "instagram": "jasminepaolini",       "ranking": 8},
    {"name": "Victoria Mboko",       "slug": "Victoria_Mboko",       "instagram": "victoriamboko",        "ranking": 9},
    {"name": "Elina Svitolina",      "slug": "Elina_Svitolina",      "instagram": "elisvitolina",         "ranking": 10},
    {"name": "Karolina Muchova",     "slug": "Karolína_Muchová",     "instagram": "karolinamuchova",      "ranking": 11},
    {"name": "Belinda Bencic",       "slug": "Belinda_Bencic",       "instagram": "belindabencic",        "ranking": 12},
    {"name": "Linda Noskova",        "slug": "Linda_Nosková",        "instagram": "lindanoskova",         "ranking": 13},
    {"name": "Ekaterina Alexandrova","slug": "Ekaterina_Alexandrova","instagram": "ekaterinaaalexandrova","ranking": 14},
    {"name": "Marta Kostyuk",        "slug": "Marta_Kostyuk",        "instagram": "marta.kostyuk",        "ranking": 15},
    {"name": "Naomi Osaka",          "slug": "Naomi_Osaka",          "instagram": "naomiosaka",           "ranking": 16},
    {"name": "Iva Jovic",            "slug": "Iva_Jovic",            "instagram": "ivajovic",             "ranking": 17},
    {"name": "Clara Tauson",         "slug": "Clara_Tauson",         "instagram": "claratauson",          "ranking": 18},
    {"name": "Madison Keys",         "slug": "Madison_Keys",         "instagram": "madisonkeys",          "ranking": 19},
    {"name": "Diana Shnaider",       "slug": "Diana_Shnaider",       "instagram": "diana.shnaider",       "ranking": 20},
]